#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using Logger = HelloDev.Logging.Logger;

namespace HelloDev.UI.Default.Editor
{
    public static class UIIdGenerator
    {
        private const string DefaultOutputPath = "Assets/HelloDev/UI/Generated/UIIds.cs";
        private const string DefaultNamespace = "HelloDev.UI.Default";

        public static void GenerateForDatabase(UIDatabase_SO db, string outputPath = null, string namespaceName = null)
        {
            if (db == null)
            {
                Debug.LogError("[UIIdGenerator] UIDatabase_SO is null.");
                return;
            }

            string path = string.IsNullOrWhiteSpace(outputPath) ? DefaultOutputPath : outputPath;
            string ns = string.IsNullOrWhiteSpace(namespaceName) ? DefaultNamespace : namespaceName;

            EnsureDirectoryExists(path);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by UIIdGenerator from UIDatabase_SO.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            var usedIdentifiers = new HashSet<string>();

            sb.AppendLine("    public static class ColourIds");
            sb.AppendLine("    {");
            foreach (var slot in db.ColourSlots)
            {
                if (string.IsNullOrEmpty(slot.Id) || string.IsNullOrEmpty(slot.name)) continue;
                string identifier = SanitizeIdentifier(slot.name);
                if (!usedIdentifiers.Add(identifier))
                {
                    Logger.LogWarning("UI", $"[UIIdGenerator] Duplicate identifier '{identifier}' from ColourSlot '{slot.name}'. Skipping.");
                    continue;
                }
                sb.AppendLine($"        public const string {identifier} = \"{slot.Id}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public static class FontIds");
            sb.AppendLine("    {");
            usedIdentifiers.Clear();
            foreach (var slot in db.FontSlots)
            {
                if (string.IsNullOrEmpty(slot.Id) || string.IsNullOrEmpty(slot.name)) continue;
                string identifier = SanitizeIdentifier(slot.name);
                if (!usedIdentifiers.Add(identifier))
                {
                    Logger.LogWarning("UI", $"[UIIdGenerator] Duplicate identifier '{identifier}' from FontSlot '{slot.name}'. Skipping.");
                    continue;
                }
                sb.AppendLine($"        public const string {identifier} = \"{slot.Id}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    // Prefer holding a UITheme_SO reference over these string constants.");
            sb.AppendLine("    // Use: runtime.SetActiveTheme(ThemeIds.Light) for string-based switching.");
            sb.AppendLine("    public static class ThemeIds");
            sb.AppendLine("    {");
            usedIdentifiers.Clear();
            foreach (var theme in db.Themes)
            {
                if (theme == null || string.IsNullOrEmpty(theme.name)) continue;
                string identifier = SanitizeIdentifier(theme.name);
                if (!usedIdentifiers.Add(identifier))
                {
                    Logger.LogWarning("UI", $"[UIIdGenerator] Duplicate identifier '{identifier}' from Theme '{theme.name}'. Skipping.");
                    continue;
                }
                sb.AppendLine($"        public const string {identifier} = \"{theme.name}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public static class DatabaseKeys");
            sb.AppendLine("    {");
            string dbKeyIdentifier = SanitizeIdentifier(db.name + "_KEY");
            sb.AppendLine($"        public const string {dbKeyIdentifier} = \"{db.name}\";");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[UIIdGenerator] Generated constants at {path}");
        }

        private static void EnsureDirectoryExists(string filePath)
        {
            string directory = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);
        }

        private static string SanitizeIdentifier(string value)
        {
            var sb = new StringBuilder(value.Length);
            foreach (char c in value)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }
            if (sb.Length > 0 && char.IsDigit(sb[0]))
                sb.Insert(0, '_');
            return sb.ToString();
        }
    }
}
#endif
